name: Build Minecraft Skylines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_VERSION: 17
  FABRIC_API_VERSION: 0.91.0+1.20.4
  YARN_MAPPINGS_VERSION: 1.20.4+build.3
  FABRIC_LOADER_VERSION: 0.15.6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Build with Gradle
        run: gradle build -PfabricApiVersion=${{ env.FABRIC_API_VERSION }} -PyarnMappingsVersion=${{ env.YARN_MAPPINGS_VERSION }} -PfabricLoaderVersion=${{ env.FABRIC_LOADER_VERSION }}

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: minecraft-skylines-alpha-jar
          path: build/libs/*.jar
