name: Build Minecraft Skylines

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Prepare libs directory
        run: mkdir -p libs

      - name: Download Fabric API
        run: |
          curl -L -o libs/fabric-api-0.97.3+1.20.4.jar https://cdn.modrinth.com/data/P7dR8mSH/versions/ZhW3FwCK/fabric-api-0.97.3%2B1.20.4.jar

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build remapJar --stacktrace
